version: "3.9"

services:
  server:
    build: .
    environment:
      PORT: 8001
      DB_HOST:     ${DB_HOST:-db}
      DB_DB:       ${POSTGRES_DB:-app}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_USER:     ${POSTGRES_USER:-auth_server}
    ports:
      - "8001:8001"
    volumes:
      - .:/src
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB:       ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_USER:     ${POSTGRES_USER:-auth_server}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data:
      
        
