* OAuth Client testing server
This is a testing Open ID Connect compliant identity provider server. It aims to be particularly verbose in providing feedback to developers wishing to implement SSO using Open ID Connect into their service.

** Running

#+BEGIN_SRC sh
docker compose up
#+END_SRC

This will start the server itself, but also the required database, and a database administration
dashboard hosted on http://127.0.0.1:5050.

The credentials to log in are provided in the docker-compose.yml file under *pgadmin* with the keys (~PGADMIN_DEFAULT_EMAIL~
and ~PGADMIN_DEFAULT_PASSWORD~)

Once into the dashboard, you can add a server and use the parameters set in the docker-compose.yml file user the
*db* section, namely: ~POSTGRES_USER~, and ~POSTGRES_PASSWORD~.

** Configuration
You will need to configure at least one entry into the ~applications~ table, and one user in the ~users~ table.

For now this is mostly done through the db, but read only access to the current users and applications are available
through =admin= api route.

- admin home :: /admin
- users :: /admin/users
- applications :: /admin/applications

*DEPRECATED* Alternatively, you can build and run the server with hot binary reloading using [[https://github.com/githubnemo/CompileDaemon][CompileDaemon]]
#+BEGIN_SRC sh
make dev
#+END_SRC

** Development Dependencies
- go 1.18
- CompileDaemeon :: Used for the local dev server with automatic server rebuilding.
#+BEGIN_SRC sh
go install github.com/githubnemo/CompileDaemon@latest
#+END_SRC

** Building
#+begin_src sh
make
#+end_src

This will produce a binary: =oauth-server=, which you can run.

** Installing
#+BEGIN_SRC sh
make install
#+END_SRC

** Running
#+begin_src
Usage of oauth-server:
  -port int
    	Port to run server on (default 8001)
#+end_src

** Test suite
#+BEGIN_SRC sh
make test
#+END_SRC

** Documentation
[[file:Docs.org][link]]

** Enhancements
*** INPROGRESS Admin endpoints
- =/admin/applications=
#+BEGIN_SRC restclient
POST /admin/applications
Content-Type: application/x-www-form-urlencoded

name=Test%20App&client_id=abc1234&client_secret=98UPpuxmcnq892FUp&callback=https%3A%2F%2Fmy.callback.com%2Fcallback
#+END_SRC
- =/admin/users=
#+BEGIN_SRC restclient
POST /admin/users
Content-Type: application/x-www-form-urlencoded

email=bob.bobson%40test.com%0A&password=super_secret&family_name=Bobson&given_name=Bob
#+END_SRC
*** TODO add config for which flows are accepted
*** TODO Nomad + consul for full application deployment
*** TODO [#B] Handle RS256 JWT signing alg
**** TODO need to provide jwks url
*** TODO Session management
[[https://openid.net/specs/openid-connect-session-1_0.html][openid docs]]
*** SOMEDAY Handle different =response_type= flows
